ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "depositAmount" FLOAT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "depositOrderId" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "depositPaymentId" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "depositStatus" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "attendanceStatus" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "attendanceMarkedAt" TIMESTAMP(3);
