ALTER TABLE "User" ADD COLUMN "notifyNewBooking" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "notifyCancellation" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "notifyDailySummary" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "gstNumber" TEXT;
ALTER TABLE "User" ADD COLUMN "businessName" TEXT;
ALTER TABLE "User" ADD COLUMN "upiId" TEXT;
